persistence:
  enabled: true
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  size: 2Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    nginx:
      json: |
        {
          "title": "Nginx Service Health",
          "panels": [
            {
              "type": "graph",
              "title": "Pod Readiness",
              "targets": [
                { "expr": "kube_pod_status_ready{namespace=\"default\",condition=\"true\"}" }
              ]
            }
          ]
        }
